### PR TITLE
Update SwiftLint

### PR DESCRIPTION
**Pull request by knightbenax**

### CODE REVIEW

**Comment by will-lumley** [comment]
Hey knightbenax,
Thanks for setting up this PR, this is great.
The failed unit tests seem to be unrelated to your changes, so I will be looking into them tonight.

**Comment by will-lumley** [comment]
Hey @knightbenax - I just realised that the package you're replacing the official SwiftLint repository by is from an unknown source of `SimplyDanny`. Can you explain why this is a better option?

**Comment by knightbenax** [comment]
@will-lumley that's the source that is on the official SwiftLint repository - [https://github.com/realm/SwiftLint](https://github.com/realm/SwiftLint)

**Comment by will-lumley** [comment]
Hi @knightbenax - apologies but I think I'm confused.
In your PR you have changed the repository from https://github.com/realm/SwiftLint to https://github.com/SimplyDanny/SwiftLintPlugins. This is not the offical SwiftLint repository.

Screenshot 2024-07-30 at 10 02 33 PM

**Comment by knightbenax** [comment]
@will-lumley do check the ReadME from [https://github.com/realm/SwiftLint](https://github.com/realm/SwiftLint) it has changed the SPM url to `https://github.com/SimplyDanny/SwiftLintPlugins` now

**Comment by will-lumley** [comment]
@knightbenax Great catch, thanks for walking me through that. Approved.

**Review by will-lumley — APPROVED** [review]

**Comment by knightbenax** [comment]
@will-lumley anytime

**Pull request merged**
